// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGylt52M7uLRLlhHhb56VsIqFfnx0uQHY',
    appId: '1:43430601180:web:209c07d87e81a380022f19',
    messagingSenderId: '43430601180',
    projectId: 'whatsapp-aa4c6',
    authDomain: 'whatsapp-aa4c6.firebaseapp.com',
    storageBucket: 'whatsapp-aa4c6.appspot.com',
    measurementId: 'G-HDZWDXZ2D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBuRA3IPO2LkGyud523_9t2orwK5mcbkE',
    appId: '1:43430601180:android:6c11b7dab4aefe20022f19',
    messagingSenderId: '43430601180',
    projectId: 'whatsapp-aa4c6',
    storageBucket: 'whatsapp-aa4c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JQGoniZdQ6fP3jvTqWcHixKs_KEhd2g',
    appId: '1:43430601180:ios:3676f6939a7b9fbb022f19',
    messagingSenderId: '43430601180',
    projectId: 'whatsapp-aa4c6',
    storageBucket: 'whatsapp-aa4c6.appspot.com',
    iosBundleId: 'com.example.whatsappchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JQGoniZdQ6fP3jvTqWcHixKs_KEhd2g',
    appId: '1:43430601180:ios:3676f6939a7b9fbb022f19',
    messagingSenderId: '43430601180',
    projectId: 'whatsapp-aa4c6',
    storageBucket: 'whatsapp-aa4c6.appspot.com',
    iosBundleId: 'com.example.whatsappchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGylt52M7uLRLlhHhb56VsIqFfnx0uQHY',
    appId: '1:43430601180:web:f91b7269502fbb35022f19',
    messagingSenderId: '43430601180',
    projectId: 'whatsapp-aa4c6',
    authDomain: 'whatsapp-aa4c6.firebaseapp.com',
    storageBucket: 'whatsapp-aa4c6.appspot.com',
    measurementId: 'G-25Y2FP4YN1',
  );
}
